package com.example.a22100213_proyectointegrador_logarismos.Semantico;

public enum TipoExpresion {
    T1_ARITMETICA,
    T2_ALGEBRA_FUNC,
    T3_DERIVADA,
    T4_INTEGRAL_INDEFINIDA,
    T5_INTEGRAL_DEFINIDA,
    T6_DESPEJE_LINEAL,
    T7_DESPEJE_POLINOMICO,
    T8_SISTEMA_EC,
    T9_IMAGINARIOS,

    ST_SIMPLE,
    ST_POLINOMICA,
    ST_TRIGONOMETRICA,
    ST_EXPONENCIAL_LOG,
    ST_RACIONAL,
    ST_RADICAL
}
